language: node_js
sudo: false
node_js:
  - 10.15.3
env:
  - NODE_ENV="test"
services:
  - postgresql
before_script:
  - yarn db:setup:user
  - yarn db:reset
script:
  - yarn lint
  - yarn test
  - yarn enforce
